name: release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name to create"
        required: true

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          platforms: ${{ steps.buildx.outputs.platforms }}
          context: .
          file: build/Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ github.event.inputs.tag_name }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create and push tag
        run: |
          git tag "${{ github.event.inputs.tag_name }}"
          git push origin "${{ github.event.inputs.tag_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
